# TODO: Prefix all env vars with service name
# TODO: Allow specifing the image tag to use
version: "3"

services:
  # base service builder
  builder:
    image: ethereumoptimism/builder
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.monorepo

  # deployer:
  #   image: ethereumoptimism/deployer
  #   build:
  #     context: ..
  #     dockerfile: ./ops/docker/Dockerfile.deployer
  #   entrypoint: ./deployer.sh
  #   environment:
  #       FRAUD_PROOF_WINDOW_SECONDS: 0
  #       L1_NODE_WEB3_URL: https://ropsten.infura.io/v3/b8568eafd70b4774839ea54532ccb6f2
  #       DEPLOYER_PRIVATE_KEY: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
  #       SEQUENCER_PRIVATE_KEY: "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
  #       NO_COMPILE: 1
  #   ports:
  #       # expose the service to the host for getting the contract addrs
  #     - ${DEPLOYER_PORT:-8080}:8081

  dtl:
    depends_on:
      - l2geth
    image: ethereumoptimism/data-transport-layer
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.data-transport-layer
    # override with the dtl script and the env vars required for it
    entrypoint: ./dtl.sh
    env_file:
      -  ./envs/dtl.env
    # set the rest of the env vars for the network whcih do not
    # depend on the docker-compose setup
    environment:
        # used for setting the address manager address
        URL: http://10.0.0.125:8080/addresses.json
        # connect to the 2 layers
        DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: https://ropsten.infura.io/v3/bdae7d6d8029490fa7ca1c55bdf6c36b
        DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT: http://l2geth:8545
        DATA_TRANSPORT_LAYER__L2_CHAIN_ID: 429
    ports:
      - ${DTL_PORT:-7878}:7878

  l2geth:
    image: ethereumoptimism/l2geth
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.geth
    # override with the geth script and the env vars required for it
    entrypoint: sh ./geth.sh
    env_file:
      - ./envs/geth.env
    environment:
        ETH1_HTTP: https://ropsten.infura.io/v3/bdae7d6d8029490fa7ca1c55bdf6c36b
        ROLLUP_STATE_DUMP_PATH: http://10.0.0.125:8080/state-dump.latest.json
        # used for getting the addresses
        URL: http://10.0.0.125:8080/addresses.json
        # connecting to the DTL
        ROLLUP_CLIENT_HTTP: http://dtl:7878
        ETH1_CTC_DEPLOYMENT_HEIGHT: 8
        RETRIES: 60
        ROLLUP_POLL_INTERVAL_FLAG: 30000ms
        MVM_GAS_ORACLE_PRICE: 1000
        MVM_GAS_ORACLE_ADDRESS: "0x420000000000000000000000000000000000000F"
    volumes:
      - ~/tmp/l2data:/root/.ethereum

    ports:
      - ${L2GETH_HTTP_PORT:-8545}:8545
      - ${L2GETH_WS_PORT:-8546}:8546
      - ${L2GETH_NODE_PORT:-30303}:30303

  l2geth-peer:
    depends_on:
      - l2geth
    image: ethereumoptimism/l2geth-peer
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.geth.peer
    # override with the geth script and the env vars required for it
    entrypoint: sh ./geth-peer.sh
    env_file:
      - ./envs/geth-peer.env
    environment:
        ETH1_HTTP: https://ropsten.infura.io/v3/bdae7d6d8029490fa7ca1c55bdf6c36b
        ROLLUP_STATE_DUMP_PATH: http://10.0.0.125:8080/state-dump.latest.json
        # used for getting the addresses
        URL: http://10.0.0.125:8080/addresses.json
        # connecting to the DTL
        ROLLUP_CLIENT_HTTP: http://dtl:7878
        L2_URL: http://l2geth:8545
        ETH1_CTC_DEPLOYMENT_HEIGHT: 8
        RETRIES: 60
        ROLLUP_POLL_INTERVAL_FLAG: 30000ms
        MVM_GAS_ORACLE_PRICE: 1000
        MVM_GAS_ORACLE_ADDRESS: "0x420000000000000000000000000000000000000F"
    ports:
      - ${L2GETH_HTTP_PORT:-10545}:8545
      - ${L2GETH_WS_PORT:-10546}:8546
      - ${L2GETH_NODE_PORT:-30304}:30303
      
  relayer:
    depends_on:
      - l2geth
    image: ethereumoptimism/message-relayer
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.message-relayer
    entrypoint: ./relayer.sh
    environment:
        L1_NODE_WEB3_URL: https://ropsten.infura.io/v3/bdae7d6d8029490fa7ca1c55bdf6c36b
        L2_NODE_WEB3_URL: http://l2geth:8545
        URL: http://10.0.0.125:8080/addresses.json
        # a funded hardhat account
        L1_WALLET_KEY: "0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97"
        RETRIES: 60
        POLLING_INTERVAL: 500
        GET_LOGS_INTERVAL: 500
        USE_CHAIN_STORE: "false"
        STORE_DB_URL: ""

  batch_submitter:
    depends_on:
      - l2geth
    image: ethereumoptimism/batch-submitter
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.batch-submitter
    entrypoint: ./batches.sh
    env_file:
      - ./envs/batches.env
    environment:
        L1_NODE_WEB3_URL: https://ropsten.infura.io/v3/bdae7d6d8029490fa7ca1c55bdf6c36b
        L2_NODE_WEB3_URL: http://l2geth:8545
        URL: http://10.0.0.125:8080/addresses.json
        SEQUENCER_PRIVATE_KEY: "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"


